training_data_paths:
  - "./scripts/tsmixup-data.arrow"
  - "./scripts/kernelsynth-data.arrow"
probability:
  - 0.9
  - 0.1
context_length: 64
prediction_length: 32
min_past: 60
max_steps: 20_000
save_steps: 10_000
log_steps: 100
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch
num_samples: 20
shuffle_buffer_length: 10_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-tiny
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
