training_data_paths:
- "/home/shane/projects/chronos-forecasting/scripts/kernelsynth-data.arrow"
probability:
- 1.0
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 100
save_steps: 50
log_steps: 10
per_device_train_batch_size: 8
learning_rate: 0.002
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 10
gradient_accumulation_steps: 1
model_id: google/t5-efficient-small
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: false
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
