# From In-domain
- name: taxi_30min # 30 min
  hf_repo: autogluon/chronos_datasets
  offset: -48
  prediction_length: 48
  num_rolls: 1
# From Zero-shot
- name: ETTh # Hourly
  hf_repo: autogluon/chronos_datasets_extra
  offset: -24
  prediction_length: 24
  num_rolls: 1
- name: monash_covid_deaths # Daily
  hf_repo: autogluon/chronos_datasets
  offset: -30
  prediction_length: 30
  num_rolls: 1
- name: monash_nn5_weekly # Weekly
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1
- name: monash_fred_md # Monthly
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: monash_m3_quarterly # Quarterly
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1
- name: monash_tourism_yearly # Yearly
  hf_repo: autogluon/chronos_datasets
  offset: -4
  prediction_length: 4
  num_rolls: 1