# Backtest configs for the 27 "zero-shot" datasets.
# These datasets were not seen by Chronos models during training.
- name: monash_traffic
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1
- name: monash_australian_electricity
  hf_repo: autogluon/chronos_datasets
  offset: -48
  prediction_length: 48
  num_rolls: 1
- name: ercot
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1
- name: ETTm
  hf_repo: autogluon/chronos_datasets_extra
  offset: -96
  prediction_length: 24
  num_rolls: 1
- name: ETTh
  hf_repo: autogluon/chronos_datasets_extra
  offset: -24
  prediction_length: 24
  num_rolls: 1
- name: exchange_rate
  hf_repo: autogluon/chronos_datasets
  offset: -30
  prediction_length: 30
  num_rolls: 1
- name: nn5
  hf_repo: autogluon/chronos_datasets
  offset: -56
  prediction_length: 56
  num_rolls: 1
- name: monash_nn5_weekly
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1
- name: monash_weather
  hf_repo: autogluon/chronos_datasets
  offset: -30
  prediction_length: 30
  num_rolls: 1
- name: monash_covid_deaths
  hf_repo: autogluon/chronos_datasets
  offset: -30
  prediction_length: 30
  num_rolls: 1
- name: monash_fred_md
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: m4_quarterly
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1
- name: m4_yearly
  hf_repo: autogluon/chronos_datasets
  offset: -6
  prediction_length: 6
  num_rolls: 1
- name: dominick
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1
- name: m5
  hf_repo: autogluon/chronos_datasets
  offset: -28
  prediction_length: 28
  num_rolls: 1
- name: monash_tourism_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1
- name: monash_tourism_quarterly
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1
- name: monash_tourism_yearly
  hf_repo: autogluon/chronos_datasets
  offset: -4
  prediction_length: 4
  num_rolls: 1
- name: monash_car_parts
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: monash_hospital
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: monash_cif_2016
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: monash_m1_yearly
  hf_repo: autogluon/chronos_datasets
  offset: -6
  prediction_length: 6
  num_rolls: 1
- name: monash_m1_quarterly
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1
- name: monash_m1_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -18
  prediction_length: 18
  num_rolls: 1
- name: monash_m3_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -18
  prediction_length: 18
  num_rolls: 1
- name: monash_m3_yearly
  hf_repo: autogluon/chronos_datasets
  offset: -6
  prediction_length: 6
  num_rolls: 1
- name: monash_m3_quarterly
  hf_repo: autogluon/chronos_datasets
  offset: -8
  prediction_length: 8
  num_rolls: 1