# Post evaluation results from the "Evaluate" workflow as a PR comment
name: Post Eval Metrics

on:
  # Runs with read & write privilages for the GITHUB_TOKEN
  workflow_run:
    workflows: ["Evaluate"]
    types:
      - completed

jobs:
  comment-eval-results:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      actions: read # for downloading artifacts
      pull-requests: write # for posting PR comment

    steps:
      - name: Download Eval Metrics
        uses: actions/download-artifact@v4
        with:
          name: eval-metrics
          path: eval-metrics-artifact/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Display structure of downloaded files
        run: ls -R
      
      - name: Extract PR number from file name
        id: extract-pr
        run: |
          FILE_NAME=$(ls eval-metrics-artifact/eval-ci-metrics-*.csv)
          PR_NUMBER=$(echo $FILE_NAME | sed -E 's/.*eval-ci-metrics-(.*).csv/\1/')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Read CSV
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: eval-metrics-artifact/eval-ci-metrics-${{ env.PR_NUMBER }}.csv

      - name: Create Markdown Table
        uses: petems/csv-to-md-table-action@master
        id: csv-table-output
        with:
          csvinput: ${{ steps.csv.outputs.content }}

      - name: Post Table as a Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            ### Evaluation Metrics
            ${{steps.csv-table-output.outputs.markdown-table}}
          reactions: rocket