name: Publish Python Package to PyPi

on:
  release:
    types: [published]

jobs:
  deploy-to-pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install setuptools wheel build
    - name: Build package
      run: |
        python -m build
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1